os: linux
sudo: false
language: python
python:
  - "2.7"
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"

branches:
  only:
  - master
  - /^test/.*$/

install:
  - pip install tox-travis

script:
  - tox

cache:
  - pip


